[package]

name = "rdrand"
version = "0.1.6"
authors = ["Simonas Kazlauskas <git@kazlauskas.me>"]
description = "An implementation of random number generator based on rdrand and rdseed instructions"
keywords = ["rand", "rdrand", "rdseed", "random"]
license = "ISC"
repository = "https://github.com/nagisa/rust_rdrand/"
documentation = "https://nagisa.github.io/rust_rdrand/"
build = "build.rs"

[dependencies]
rand = "0.3"
unreachable = "0.1"

[build-dependencies.llvm_build_utils]
git = "https://github.com/nagisa/llvm_build_utils.rs.git"
